language: node_js
node_js:
  - "7"
before_script:
    make clean
script:
    make build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  repo: qabc/qabc-org.github.io
  target_branch: master
  on:
    branch: 2017-site
